language: go
os:
  - osx
go:
- 1.6

install:
  - go get github.com/mitchellh/gox

script: make cross-gox-build-all-platform package-all-platform

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "czJnpGgoWFL6/0pl+KcHTDOUjIK5DD9mt3qgg/7GaECzgUpn3j4UMrsNXooFk30o7H0Dw9kiEAH/pRhCD196fRU6zV12Pt3+7FdohPkhUahXVRYrsOSKqRXxuSYqOvMH3SvoCO990icj3eVTlb4lYDKFunFyfeuvbsPtjdWIIWwEN+2vzKO+kz1HG+8LYXqH/yVVJSM2hMFxHBlGA4aTkCFtZ6pfN1EQlxeFSgep+MiR0r5tX4Osj2JHaSBFtVHWgbOtm47ZjUMEczSQvTExQoBAOn44qNZ4oA57NUKcPXgylVo+FAsRDb5VM3ndvDRJb4P2h9yBm0ioiCMh71SmfWNT2cCmGwiIhk08ggMT1n58kXfLdzAkbAnVfX+hrmxI29F+tIGdYQsoWUFaT7v29Hwukcx/FTqUcypbsuXmU7K2uiGvgaYftafOdaQLJw5eTD2TTl9jQssXfyx5xkTcYBtsHa9CSjdpKZX//MuEnmvCvXBZH6HnK06fUGIu4BQWuhGCiLEuKMTAOYO5u4q0MaQ5ts1rI8jb39fboIoSkgw9CYUDG2qCHzjIUEEKWM1KqY3JNHdQxQg+p+Hk4Ig7ox7G0xFFGBsmBpTVFp4ojzmBRgEUp9uksr42BnOSn/Gpq4S2PtITJ9OgXn2e4IPztnXHocaM14MPj4kRUVx4DAI="
  file: 'bin/*.tar.gz'
  file_glob: true
  on:
    repo: hawkingrei/elasticsearch-migration
    tags: true
