language: go
os:
  - osx
go:
- 1.6

install:
  - go get github.com/mitchellh/gox

script: make cross-gox-build-all-platform package-all-platform

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Yt+sj+iPZyVRAVBXXXBd54syxUcKziRsR5cd8cwXz/uT3RIWyzeX+Roo+XZjEMxt85WTcyBrBnne6Iq2ley6z4ke6KRZx123m2IWPLOcXwW9SsLKeh0JEvow2oo5vLl3IhPnX10BNRiP4QwkpIVBfJqUCNnC6NS2VqZEDpmwYeYeY20G7psTt09quz9kTCaatkop8UpUwwHqIvAwYj8QSA1FS44bJJPLY5RBcx1r3tI6WQEwnXbrqoW7CkeRg9gaK9WAJQJ6WSUUyYierHyZX5SzUmV9CJoO7E5V287P5+i99+GGpYxKJlMPV9La2Fnd0QMNDe4sp2q9ZNjXxeVI12nA30S6WG4hNmxdELImMpRI17WhaU0SOl5TnhbSUDtP3TYzOlm4ZiClIYCd0lDdMCw+iEazIUgh2kz9rT5kec38R1Nl09zoMGmnsCzhiUSplx9wU8HjfX/gxPr0ec+WQ+HjFlhld+Zd9NDNXHeHJfzItJe+ApG7lrkB5ZsN/BKtQ8BW8vmBpPwKvgcpAnqKztKpCLbHh1Cadz9TPRRGyhyaisBA+HG8sxjrPQiGaEY8eUl3kQOhhVeHNf5zt3H6T6jIPdkH3VqQ5Jez4SMZkitN27IU8oT8a/FZC8+tgEZQgFZKcV0PSUIkU3xvIdkYeUivhpWfHdt+erpmiQEWE5w=
  file: 'bin/*.tar.gz'
  file_glob: true
  on:
    repo: hawkingrei/elasticsearch-migration
    tags: true
